### ISSUE TITLE
Persistent Notification on pausing playback

### ISSUE THREAD

**Issue by jssingh** [android/uamp#265]
This is more of a question. Any help would be deeply appreciated.
The kotlin code is quite a bit simpler than its java equivalent for a number of reasons. One of the more interesting things that stood out to me was the notification behavior. 

In the Java code, when pausing playback, the notification (and service) would be killed after a minute or so by the OS, especially on Oreo and above. This is the default behavior.

In the Kotlin version, even when pausing the playback, the notification stays intact for music to potentially resume in the future. The notification does not get killed by the OS. Also noticed that "setOngoing" is not called on the notification which relies on PlaybackState. **How are we achieving this?** Would it be because of the exoplayer mediasession extension?

How should be go about retaining the notification in the java version?

Thanks!

**Comment by nic0lette** [comment]
I haven't looked in awhile, so I'm going from memory/quickly looking over the code.

The service is stopped when the player is stopped/in the background because of the class `DelayedStopHandler` that's part of [MusicService](https://github.com/googlesamples/android-UniversalMusicPlayer/blob/f3154af7ac972ee9b7b1fd32ca3c935e02268a18/mobile/src/main/java/com/example/android/uamp/MusicService.java#L418-L437).

The notification is removed because it's asked to be removed in [MusicService.onDestroy](https://github.com/googlesamples/android-UniversalMusicPlayer/blob/f3154af7ac972ee9b7b1fd32ca3c935e02268a18/mobile/src/main/java/com/example/android/uamp/MusicService.java#L292).

The notification doesn't need to have `setOngoing` set because when the service is in the foreground, it's ongoing by default, and cannot be swiped away. When it's paused, then it doesn't need that.

To get the notification to stick around, I'd start by trying to remove the call to `mMediaNotificationManager.stopNotification();` in `MusicService.onDestroy`.

The complexity in the Java version is one of the reasons I decided to rewrite it completely in Kotlin, rather than porting it from the existing code or just updating parts of it. =(

**Comment by kerneltea** [comment]
> I haven't looked in awhile, so I'm going from memory/quickly looking over the code.
> 
> The service is stopped when the player is stopped/in the background because of the class `DelayedStopHandler` that's part of [MusicService](https://github.com/googlesamples/android-UniversalMusicPlayer/blob/f3154af7ac972ee9b7b1fd32ca3c935e02268a18/mobile/src/main/java/com/example/android/uamp/MusicService.java#L418-L437).
> 
> The notification is removed because it's asked to be removed in [MusicService.onDestroy](https://github.com/googlesamples/android-UniversalMusicPlayer/blob/f3154af7ac972ee9b7b1fd32ca3c935e02268a18/mobile/src/main/java/com/example/android/uamp/MusicService.java#L292).
> 
> The notification doesn't need to have `setOngoing` set because when the service is in the foreground, it's ongoing by default, and cannot be swiped away. When it's paused, then it doesn't need that.
> 
> To get the notification to stick around, I'd start by trying to remove the call to `mMediaNotificationManager.stopNotification();` in `MusicService.onDestroy`.
> 
> The complexity in the Java version is one of the reasons I decided to rewrite it completely in Kotlin, rather than porting it from the existing code or just updating parts of it. =(

Hello, @nic0lette  . I think the one-minute garbage collection talked by @jssingh is not the "stop" invoked by DelayedStopHandler, but is the garbage collection of Android O system. I am also in such a situation: in Kotlin, the service could be kept still without being collected; however, in Java, this could not be achieved. How to make this? I tried to use Exoplayer mediasession extension, but failed.

**Comment by jssingh** [comment]
> > I haven't looked in awhile, so I'm going from memory/quickly looking over the code.
> > The service is stopped when the player is stopped/in the background because of the class `DelayedStopHandler` that's part of [MusicService](https://github.com/googlesamples/android-UniversalMusicPlayer/blob/f3154af7ac972ee9b7b1fd32ca3c935e02268a18/mobile/src/main/java/com/example/android/uamp/MusicService.java#L418-L437).
> > The notification is removed because it's asked to be removed in [MusicService.onDestroy](https://github.com/googlesamples/android-UniversalMusicPlayer/blob/f3154af7ac972ee9b7b1fd32ca3c935e02268a18/mobile/src/main/java/com/example/android/uamp/MusicService.java#L292).
> > The notification doesn't need to have `setOngoing` set because when the service is in the foreground, it's ongoing by default, and cannot be swiped away. When it's paused, then it doesn't need that.
> > To get the notification to stick around, I'd start by trying to remove the call to `mMediaNotificationManager.stopNotification();` in `MusicService.onDestroy`.
> > The complexity in the Java version is one of the reasons I decided to rewrite it completely in Kotlin, rather than porting it from the existing code or just updating parts of it. =(
> 
> Hello, @nic0lette . I think the one-minute garbage collection talked by @jssingh is not the "stop" invoked by DelayedStopHandler, but is the garbage collection of Android O system. I am also in such a situation: in Kotlin, the service could be kept still without being collected; however, in Java, this could not be achieved. How to make this? I tried to use Exoplayer mediasession extension, but failed.

That is correct @nic0lette . Your suggestions don't quite seem to work for Java. As soon as you pause music, a minute after the notification is killed because the service is killed in the background. Kotlin seems to get around the issue nicely. 

Wondering if you had any more thoughts. Thanks!

**Comment by dturner** [comment]
The way that notifications are handled has been refactored. Closing as obsolete.
