### ISSUE TITLE
How to add custom action?

### ISSUE THREAD

**Issue by Zialynn-Anderson-Bose** [android/uamp#287]
Could you please add or explain where / how to add custom actions to the controls?

**Comment by xyz-fly** [comment]
like this:
1. create receiver that implements  MediaSessionConnector.CommandReceiver
2. connector.registerCustomCommandReceiver
3. mediaSessionConnection.sendCommand
4. do something in the method of onCommand(MediaSessionConnector.CommandReceiver)

**Comment by nic0lette** [comment]
There's a custom command implemented in the automotive module for handling signing in, with the core implementation of that being in the [`AutomotiveCommandReceiver`](https://github.com/android/uamp/blob/22116073f1c87c6b7daed35c0c80029084b69eda/automotive/src/main/java/com/example/android/uamp/automotive/AutomotiveMusicService.kt#L117-L178) class.

Hopefully that helps, otherwise it's probably best to ask on [Stack Overflow](https://stackoverflow.com/) for more specific guidance.
