### ISSUE TITLE
Build Error: API 'variant.getPackageLibrary()' is obsolete and has been replaced with 'variant.getPackageLibraryProvider()'.

### ISSUE THREAD

**Issue by eturk1** [android/uamp#305]
just imported into Android Studio & receive this build error. 
Is UAMP an abandoned project? Is there a current maintained example project for AA media player?

![image](https://user-images.githubusercontent.com/525280/68920515-4ec86c00-072a-11ea-8c52-970b27945fc7.png)

**Comment by nic0lette** [comment]
This is not a build error, but a warning. Following through with the suggestion in the warning (namely "use -Pandroid.debug.obsoleteApi=true on the command line to display more information") results in this:

```
WARNING: API 'variant.getPackageLibrary()' is obsolete and has been replaced with 'variant.getPackageLibraryProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
REASON: The Kotlin plugin is currently calling this API. We are working to solve this.
```

I have the utmost confidence that JetBrains will update the plugin in time for the removal.

Since this is not anything related to the UAMP project itself, I'm going to close this issue. Thank you.
