### ISSUE TITLE
App crashes after pausing and dismissing the notification

### ISSUE THREAD

**Issue by wajahatkarim3** [android/uamp#316]
**How to reproduce?**
1. Play a song by opening its details screen
2. Go to home screen either by pressing back multiple times or directly home
3. From the app's notification, pause the song and dismiss the notification
4. Open the app again and it crashes.

**Expected**
The app should open normally.

**What happens?**
App crashes when attempting to launch. It throws the `IllegalStateException` . Here's the full stacktrace:

```
2020-01-20 15:30:13.638 15478-15478/com.example.android.uamp.next E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.android.uamp.next, PID: 15478
    java.lang.IllegalStateException: getString(MediaMetadataC…at.METADATA_KEY_MEDIA_ID) must not be null
        at com.example.android.uamp.viewmodels.MediaItemFragmentViewModel.getResourceForMediaId(MediaItemFragmentViewModel.kt:186)
        at com.example.android.uamp.viewmodels.MediaItemFragmentViewModel.access$getResourceForMediaId(MediaItemFragmentViewModel.kt:42)
        at com.example.android.uamp.viewmodels.MediaItemFragmentViewModel$subscriptionCallback$1.onChildrenLoaded(MediaItemFragmentViewModel.kt:69)
        at android.support.v4.media.MediaBrowserCompat$MediaBrowserImplApi21.onLoadChildren(MediaBrowserCompat.java:1958)
        at android.support.v4.media.MediaBrowserCompat$CallbackHandler.handleMessage(MediaBrowserCompat.java:2120)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7397)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

**Comment by lovisgod** [comment]
I will like to take up this issue.

**Comment by dturner** [comment]
This was a fun one to debug! 

Firstly, some specifics about when the error occurs: 

- First we run the app and start playback.
- This causes `MusicService` to start itself as a service by calling `startForegroundService`.
- Then we kill the Activity which also kills the foreground notification (this behaviour might vary depending on API level but that's what happens on my Pixel 3 running API 29).
- Critically `MusicService` is still running at this point - the system will kill it off eventually because it now lacks a foreground notification but it will stay running for long enough for us to restart the app. 
- Restarting the app causes the it to crash on startup with the error described.

What's going on inside the app when it crashes:

- The bug occurs when the list of media items is loaded and `MediaItemFragmentViewModel.subscriptionCallback.onChildrenLoaded` is called.
- Inside this function we call `getResourceForMediaId` and pass in a `mediaId` String with the value `__RECOMMENDED__`.
- We now do a comparison with the currently playing item. For this we use our `musicServiceConnection` which was obtained through `MusicServiceConnection.getInstance()` (this will become important shortly).
- We obtain `musicServiceConnection.nowPlaying.value?.id` which causes our extension function `MediaMetadataCompat.id.get()` to be called. This returns a `String`, not a `String?` so nulls are not allowed. 
- When it calls the underlying method `MediaMetadataCompat.getString(MediaMetadataCompat.METADATA_KEY_MEDIA_ID)` it returns a null. Hence the crash. 

So, how was it possible that we ended up with a null value for the `MediaMetadataCompat.METADATA_KEY_MEDIA_ID` key? 

- This happens inside `MusicServiceConnection::MediaControllerCallback::onMetadataChanged` when the activity is swiped away. 
- Critically because `MusicService` doesn't immediately die when this happens, it also holds a reference to the singleton `MusicServiceConnection` so when the app restarts it *reuses* that same `MusicServiceConnection`, avoiding the usual startup code which sets the metadata to `NOTHING_PLAYING`, that's why it doesn't crash the first time. 

The solution is now pretty simple, just add a check to `onMetadataChanged` and if the id is null set the `nowPlaying` value to `NOTHING_PLAYING`. PR to follow.  

There are some bigger questions here though: 

- When using kotlin extension functions, should one change the nullability of a field when they can't stop null being written to that field?
- Should `MusicService` be destroyed as soon as both the notification and the activity are destroyed? This would avoid any object reuse between app starts which is probably a good thing.
