### ISSUE TITLE
How to avoid Sign.in activity for Automotive OS app ?

### ISSUE THREAD

**Issue by RajasekarGovindaraj** [android/uamp#351]
hello there,

I'm creating a standalone music player app for automotive OS using UAMP sample as reference code.
My intention is to not have a sign in activity and directly launching the music player.
Since i'm new to kotlin can some support here to understand flow ?
thanks in advance.

**Comment by frankkienl** [comment]
There is a sign-in check in `com.example.android.uamp.automotive.AutomotiveMusicService`.

If you remove the check there, it won't prompt for signing in anymore.

**Comment by frankkienl** [comment]
If you want to remove signing in altogether, you can remove all `Activity`-classes from the Automotive module (and their AndroidManifest.xml entries), and remove all code from `com.example.android.uamp.automotive.AutomotiveMusicService`;
So that the file `com.example.android.uamp.automotive.AutomotiveMusicService` reads no more than:

```
package com.example.android.uamp.automotive
import com.example.android.uamp.media.MusicService
class AutomotiveMusicService : MusicService() { }
```

**Comment by nic0lette** [comment]
I'm going to close this since @frankkienl answered this (Thank you!) :)

(I will also add that _if_ you did remove the activities from the automotive module, you could also remove `AutomotiveMusicService` and simply use `MusicService` to perform the playback at that point.)
