### ISSUE TITLE
Android Auto stopped seeing uamp

### ISSUE THREAD

**Issue by pawga** [android/uamp#438]
A media application availability issue has been identified. I don’t understand what is the matter, since there was no such problem before.

1. Installing the application uamp.
2. Open Android Auto (for example, version 6.1.610544-release).
3. Uamp is not present in the lists of media applications  :(.

**Comment by nic0lette** [comment]
Because of safety concerns, only apps which pass a review process are permitted to run on Android Auto.

It's possible to enable any Auto compatible app to be run with Android Auto by using the developer settings menu to [enable "unknown sources"](https://developer.android.com/training/cars/testing#step1)
